### ISSUE TITLE
`DurableObjectState` missing `name` property

### ISSUE THREAD

**Issue by rennokki** [cloudflare/workers-types#180]
DO states from DO that was generated with name are not being hinted at by the editor properly. 

```typescript
constructor(protected state: DurableObjectState, protected env) {
    let string = state.id.name; // type hints as error?
}
```

It should be defined as `name?: string;`

**Comment by koeninger** [comment]
The type of DurableObjectState.id can be either string or DurableObjectId, https://github.com/cloudflare/workers-types/blob/f4f7e094e6d6b7685d05a4eaf68f557591073c76/index.d.ts#L332
You'll need to cast it or otherwise narrow the type.

Furthermore, as things stand today, state.id.name as passed to the constructor is going to be undefined; a DurableObjectId returned from .idFromName will have a name however.

Typical workaround currently if you need access to the name is to pass it in the request; can you say a little more about your use case for accessing it in the constructor?

**Comment by rennokki** [comment]
You're right. The `state.id.name` is indeed undefined. 😅
