### ISSUE TITLE
TS2339: Property 'body' does not exist on type 'R2ObjectBody | R2Object'.   Property 'body' does not exist on type 'R2Object'.

### ISSUE THREAD

**Issue by joberthar** [cloudflare/workers-types#270]
When trying to return a new response for an R2 object, there is an error that `body` does not exist in the type `R2Object` or `R2ObjectBody`.

Example script:

```
interface Env {
    MY_BUCKET: R2Bucket
}
export default {
    async fetch(request: Request, env: Env): Promise <Response> {
        try {
            const url = new URL(request.url);
            const objectKey = url.pathname.slice(1);
            const object = await env.MY_BUCKET.get(objectKey, {
                onlyIf: request.headers,
            });

            const headers = new Headers();

            const response = new Response(object.body, {
                headers,
            });

            return response;
        } catch (e) { console.error(e) }
    }
}
```

**Comment by KianNH** [comment]
Your onlyIf conditional will return the object without a body if the conditional fails - does this still happen if you remove that?

**Comment by justinjett** [comment]
Even when I remove the `onlyIf` conditional from `object`, I receive the error.

**Comment by KianNH** [comment]
I might have misinterpreted your issue - I was thinking of runtime errors (i.e `request.body is undefined`) as opposed to TypeScript having issues when type checking.

If you're *not* using `onlyIf` conditionals, you need to make sure that `object` is not `null`/`undefined` since that's what R2 will return if there is no object present.

<img width="554" alt="image" src="https://user-images.githubusercontent.com/94662631/183309252-999e9d44-268c-439c-a00c-a11991d4ae9d.png">

In the end, it'd look like so:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/94662631/183309422-436ebe32-f8fa-475c-8c70-f9f25418f88d.png">

```ts
const object = await env.MY_BUCKET.get(objectKey);

if (object === null) {
	return new Response(`${objectKey} not found`);
}

const headers = new Headers();
headers.set("etag", object.httpEtag);
object.writeHttpMetadata(headers);

return new Response(object.body, {
	headers,
});
```

I've added the 'proper' header handling since you'll want to write your stored `httpMetadata` and `eTag` onto the response.

As for handling `onlyIf` conditionals that fail & return `R2Object` with no body, take a look at how this project handles them: https://github.com/kotx/render/blob/master/src/index.ts#L109
