### ISSUE TITLE
KVNamespace declared differently than other interfaces

### ISSUE THREAD

**Issue by jdanyow** [cloudflare/workers-types#33]
Why is the KVNamespace declared differently than the rest of the interfaces?

https://github.com/cloudflare/workers-types/blob/6340625225f3ec80bdecf765436d39240bc367aa/index.d.ts#L443-L444

Would it be better to reference the types like this?
```json
{
  "extends": "../../tsconfig-base",
  "compilerOptions": {
    "target": "esnext",
    "lib": ["webworker", "esnext"],
    "composite": false,
    "types": ["@cloudflare/workers-types"]
  }
}
```
Just thinking the instructions in the README are strange with respect to the empty import:
> **Usage**
> Just supply an empty import in one of your source files to receive the workers types
> ```js
> import {} from '@cloudflare/workers-types'
> ```

Might be considered an unused import by formatters/linters.

**Comment by 1000hz** [comment]
I think this is a great suggestion. The usage of `declare module` here is definitely incorrect. I agree, our recommendation for usage is a bit clunky, including it via `types` is the way to go. I was initially unsure if that'd be a good idea since specifying `types` would preclude automatic inclusion of any `@types/*` packages, but I realize now that's largely irrelevant since most of those packages would be providing types for modules that are imported, not global.
