### ISSUE TITLE
Publish new version after 2.1.0

### ISSUE THREAD

**Issue by jayphelps** [cloudflare/workers-types#82]
Hey folks! Just a friendly bump if someone has npm publish access. There have been quite a number of changes since the last release. We've just been copy-pasting the source here into our own definition file, so we're not blocked per-say. Thanks 🚀

**Comment by jrf0110** [comment]
Oh wow. Looks like there's been a ton of merges since 2.1.0 https://github.com/cloudflare/workers-types/commits/master

A number of these changes are "breaking" in that it could cause type errors in other folks' projects. However, they are _more correct_ typings. I say we do a minor version bump to `2.2.0`. Any objects to me doing that @koeninger

**Comment by jayphelps** [comment]
One sec, gonna PR a fix for metroCode btw

**Comment by koeninger** [comment]
@jrf0110 sounds good to me

**Comment by jrf0110** [comment]
Published `2.2.0`
